config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create, :update] do
    resources :doses, only: [:new, :create, :delete, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses 
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient_id, uniqueness: {scope: :cocktail_id}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    def index 
        @cocktails = Cocktail.all
    end 
    
    def show
        @cocktail = Cocktail.find(params[:id])
    end    

    def new
        @cocktail = Cocktail.new
    end    

    def update

    end

    def create

        @cocktail = Cocktail.new(cocktail_params)
        if @cocktail.save
          redirect_to @cocktail
        else
          render :new
        end
      end
    
      private
    
      def cocktail_params
        params.require(:cocktail).permit(:name)
      end
    
    end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

    def new
        
    end

    def create

    end    

    def delete

    end    

    def update

    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1> Welcome to Cocktails Bar </h1>

    <ul class="list-group">
        <% @cocktails.each do |cocktail| %>
          <li class="list-group-item">
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </li>
        <% end %>
    </ul>
       <%= link_to "Add a new Cocktail", new_cocktail_path, class: 'btn btn-primary' %>

app/views/cocktails/new.html.erb
<h1> Time to get drunk </h1>

    <%= simple_form_for [@cocktail] do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-warning' %>
      <% end %>

    <%= link_to "See all cocktails", cocktails_path %>

app/views/cocktails/show.html.erb
<h1> Update a cocktail </h1>

<%= simple_form_for [@cocktail] do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <%= link_to "See all cocktails", cocktails_path %>
      <br>
      <%= link_to "Add at dose", new_cocktail_dose_path(@cocktail) %>
      

app/views/doses/new.html.erb
<h1> This is doses </h1>

        <%= link_to "See all cocktails", cocktails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>